In [158]:
# random functions
import numpy as np
40*np.random.random()+2

15.610310936677834

In [169]:
30*np.random.random([3,3])+2

array([[20.24610294, 27.805386  , 26.80739332],
       [ 3.80261096, 30.73403713, 30.94303851],
       [22.9492959 , 17.44378471, 19.00006539]])

In [188]:
np.random.randint(1,20,[3,3])

array([[18,  4,  9],
       [ 1, 12, 15],
       [10, 17,  4]])

In [197]:
np.random.randn(5,3)

array([[ 0.06025624, -0.16982385,  0.06434791],
       [ 0.67990551,  0.85642767, -0.37273625],
       [ 0.20487519,  1.10613893, -0.93593815],
       [ 0.31412591,  2.19934166, -1.2252489 ],
       [ 2.54573194,  0.66000254,  0.06610087]])

In [200]:
np.random.choice(['a','b','c','d','e'],(3,3))

array([['c', 'd', 'b'],
       ['d', 'd', 'c'],
       ['b', 'e', 'e']], dtype='<U1')

In [203]:
# linspace
a=np.linspace(1,50,10)
a

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [204]:
a.itemsize

8

In [ ]:
# reshape()

In [213]:
np.arange(32).reshape(2,4,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [219]:
np.arange(12).reshape(2,3,-1)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [230]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [221]:
a+b

array([[ 6,  8],
       [10, 12]])

In [225]:
np.sum((a,b))

36

In [228]:
np.sum(a+b,axis=0)

array([16, 20])

In [231]:
a-b

array([[-4, -4],
       [-4, -4]])

In [232]:
np.sum(a-b)

-16

In [233]:
np.sum(a-b,axis=0)

array([-8, -8])

In [234]:
np.sum(a-b,axis=1)

array([-8, -8])

In [235]:
a*b

array([[ 5, 12],
       [21, 32]])

In [236]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [237]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [238]:
a%b

array([[1, 2],
       [3, 4]], dtype=int32)

In [239]:
# some trigonometry  function
np.sin(a)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [241]:
np.sin((a,b))

array([[[ 0.84147098,  0.90929743],
        [ 0.14112001, -0.7568025 ]],

       [[-0.95892427, -0.2794155 ],
        [ 0.6569866 ,  0.98935825]]])

In [242]:
np.cos(a)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [245]:
c=np.tan(a)
c

array([[ 1.55740772, -2.18503986],
       [-0.14254654,  1.15782128]])

In [251]:
1/c

array([[ 0.64209262, -0.45765755],
       [-7.01525255,  0.86369115]])

In [249]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [252]:
np.std(a)

1.118033988749895

In [253]:
np.median(a)

2.5

In [254]:
a

array([[1, 2],
       [3, 4]])

In [256]:
np.exp((a,b))

array([[[2.71828183e+00, 7.38905610e+00],
        [2.00855369e+01, 5.45981500e+01]],

       [[1.48413159e+02, 4.03428793e+02],
        [1.09663316e+03, 2.98095799e+03]]])

In [257]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [260]:
# linear algebra 

# 3x + 4y = 10
# 8x + 2y = 20

a=np.array([[3,4],[8,2]])
b=np.array([10,20])

np.linalg.solve(a,b)

array([2.30769231, 0.76923077])

In [263]:
# 5x + 6y + 7z =10
# 9x + 8y + 3z =20
# 2x + 9y + 5z= 30
a= np.array([[5,6,7],[9,8,3],[2,9,5]])
b=np.array([10,20,30])
np.linalg.solve(a,b)

array([-1.22377622,  4.44055944, -1.5034965 ])

In [265]:
a

array([[5, 6, 7],
       [9, 8, 3],
       [2, 9, 5]])

In [266]:
np.linalg.det(a)

286.00000000000017

In [270]:
b=np.array([[1,2],[3,4]])
np.linalg.det(b)

-2.0000000000000004

In [272]:
round(np.linalg.det(b))

-2.0

In [268]:
np.linalg.eig(a)  # eigon values

(array([18.30711252+0.j        , -0.15355626+3.94952706j,
        -0.15355626-3.94952706j]),
 array([[ 0.56305115+0.j        , -0.06978068-0.5235022j ,
         -0.06978068+0.5235022j ],
        [ 0.64281879+0.j        , -0.35948527+0.40371623j,
         -0.35948527-0.40371623j],
        [ 0.51938175+0.j        ,  0.65487377+0.j        ,
          0.65487377-0.j        ]]))

## pandas

- Data manupulation
- Data Cleaning
- Data Analysis
- Data Transformation


In [ ]:
# Data structures
- Series
- DataFrame

In [277]:
import pandas as pd
a=pd.Series([1,2,3,4,5,8.9,'d'])
a

0      1
1      2
2      3
3      4
4      5
5    8.9
6      d
dtype: object

In [279]:
a[0:7]

0      1
1      2
2      3
3      4
4      5
5    8.9
6      d
dtype: object

In [281]:
a=pd.DataFrame([[1,2,3],[4,5,6]])
a

0  1  2
0  1  2  3
1  4  5  6

In [301]:
import numpy as np
import pandas as pd

name = np.random.choice(['name1','name2','name3','name4','name5'],20)
marks=np.random.randint(1,100,size=20)
avg=np.random.choice([67,56,48,98,34],20)


In [306]:
a=list(zip(name,marks,avg))

In [307]:
df=pd.DataFrame(a,columns=['name','marks','avg1'])
df

name  marks  avg1
0   name5     37    34
1   name2     26    48
2   name2     13    34
3   name3     18    98
4   name1     86    34
5   name4     34    48
6   name2     58    56
7   name3     10    67
8   name5     50    56
9   name4     39    67
10  name2     24    34
11  name5     29    98
12  name3     48    56
13  name3     39    34
14  name4     62    56
15  name5     32    56
16  name3     79    98
17  name4     61    34
18  name3     92    98
19  name5     37    56

In [308]:
df=pd.DataFrame({'name':name,'marks':marks,'avg':avg})
df

name  marks  avg
0   name5     37   34
1   name2     26   48
2   name2     13   34
3   name3     18   98
4   name1     86   34
5   name4     34   48
6   name2     58   56
7   name3     10   67
8   name5     50   56
9   name4     39   67
10  name2     24   34
11  name5     29   98
12  name3     48   56
13  name3     39   34
14  name4     62   56
15  name5     32   56
16  name3     79   98
17  name4     61   34
18  name3     92   98
19  name5     37   56

In [309]:
d=[["name1",10],["name2",12],["name3",14]]
a=pd.DataFrame(d,columns=["name",'values'])
a

name  values
0  name1      10
1  name2      12
2  name3      14

In [317]:
df.head()

name  marks  avg
0  name5     37   34
1  name2     26   48
2  name2     13   34
3  name3     18   98
4  name1     86   34

In [315]:
df.tail(4)

name  marks  avg
16  name3     79   98
17  name4     61   34
18  name3     92   98
19  name5     37   56

In [316]:
df.shape

(20, 3)

In [319]:
df['avg'].describe()

count    20.00000
mean     58.10000
std      23.21728
min      34.00000
25%      34.00000
50%      56.00000
75%      67.00000
max      98.00000
Name: avg, dtype: float64

In [320]:
df.describe()

marks       avg
count  20.000000  20.00000
mean   43.700000  58.10000
std    23.267551  23.21728
min    10.000000  34.00000
25%    28.250000  34.00000
50%    38.000000  56.00000
75%    58.750000  67.00000
max    92.000000  98.00000

In [321]:
df.info

<bound method DataFrame.info of      name  marks  avg
0   name5     37   34
1   name2     26   48
2   name2     13   34
3   name3     18   98
4   name1     86   34
5   name4     34   48
6   name2     58   56
7   name3     10   67
8   name5     50   56
9   name4     39   67
10  name2     24   34
11  name5     29   98
12  name3     48   56
13  name3     39   34
14  name4     62   56
15  name5     32   56
16  name3     79   98
17  name4     61   34
18  name3     92   98
19  name5     37   56>

In [322]:
df.values

array([['name5', 37, 34],
       ['name2', 26, 48],
       ['name2', 13, 34],
       ['name3', 18, 98],
       ['name1', 86, 34],
       ['name4', 34, 48],
       ['name2', 58, 56],
       ['name3', 10, 67],
       ['name5', 50, 56],
       ['name4', 39, 67],
       ['name2', 24, 34],
       ['name5', 29, 98],
       ['name3', 48, 56],
       ['name3', 39, 34],
       ['name4', 62, 56],
       ['name5', 32, 56],
       ['name3', 79, 98],
       ['name4', 61, 34],
       ['name3', 92, 98],
       ['name5', 37, 56]], dtype=object)

In [327]:
df.set_index('avg',inplace=True)

In [328]:
df

name  marks
avg              
34   name5     37
48   name2     26
34   name2     13
98   name3     18
34   name1     86
48   name4     34
56   name2     58
67   name3     10
56   name5     50
67   name4     39
34   name2     24
98   name5     29
56   name3     48
34   name3     39
56   name4     62
56   name5     32
98   name3     79
34   name4     61
98   name3     92
56   name5     37

In [333]:
df.sort_values(by="marks",ascending=True)

name  marks
avg              
67   name3     10
34   name2     13
98   name3     18
34   name2     24
48   name2     26
98   name5     29
56   name5     32
48   name4     34
34   name5     37
56   name5     37
34   name3     39
67   name4     39
56   name3     48
56   name5     50
56   name2     58
34   name4     61
56   name4     62
98   name3     79
34   name1     86
98   name3     92

In [334]:
df.head()

name  marks
avg              
34   name5     37
48   name2     26
34   name2     13
98   name3     18
34   name1     86

In [337]:
df.iloc[1:6]

name  marks
avg              
48   name2     26
34   name2     13
98   name3     18
34   name1     86
48   name4     34

In [339]:
df.loc[34]

name  marks
avg              
34   name5     37
34   name2     13
34   name1     86
34   name2     24
34   name3     39
34   name4     61

In [341]:
df.loc[(df.marks>10)&(df.marks<=50)]

name  marks
avg              
34   name5     37
48   name2     26
34   name2     13
98   name3     18
48   name4     34
56   name5     50
67   name4     39
34   name2     24
98   name5     29
56   name3     48
34   name3     39
56   name5     32
56   name5     37

In [352]:
df1=pd.DataFrame([['a',2],['b',3]],columns=["letters","marks"])
df2=pd.DataFrame([['c',5],['d',6]],columns=['letters1',"marks1"])

In [353]:
df1

letters  marks
0       a      2
1       b      3

In [354]:
df2

letters1  marks1
0        c       5
1        d       6

In [355]:
pd.concat([df1,df2],ignore_index=True)

C:\Users\Lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


letters letters1  marks  marks1
0       a      NaN    2.0     NaN
1       b      NaN    3.0     NaN
2     NaN        c    NaN     5.0
3     NaN        d    NaN     6.0

In [358]:
pd.read_csv("mpg.csv")

Unnamed: 0 manufacturer               model  displ  year  cyl  \
0             1         audi                  a4    1.8  1999    4   
1             2         audi                  a4    1.8  1999    4   
2             3         audi                  a4    2.0  2008    4   
3             4         audi                  a4    2.0  2008    4   
4             5         audi                  a4    2.8  1999    6   
5             6         audi                  a4    2.8  1999    6   
6             7         audi                  a4    3.1  2008    6   
7             8         audi          a4 quattro    1.8  1999    4   
8             9         audi          a4 quattro    1.8  1999    4   
9            10         audi          a4 quattro    2.0  2008    4   
10           11         audi          a4 quattro    2.0  2008    4   
11           12         audi          a4 quattro    2.8  1999    6   
12           13         audi          a4 quattro    2.8  1999    6   
13           14         audi          a4 quattro    3.1  2008    6   
14           15         audi          a4 quattro    3.1  2008    6   
15           16         audi          a6 quattro    2.8  1999    6   
16           17         audi          a6 quattro    3.1  2008    6   
17           18         audi          a6 quattro    4.2  2008    8   
18           19    chevrolet  c1500 suburban 2wd    5.3  2008    8   
19           20    chevrolet  c1500 suburban 2wd    5.3  2008    8   
20           21    chevrolet  c1500 suburban 2wd    5.3  2008    8   
21           22    chevrolet  c1500 suburban 2wd    5.7  1999    8   
22           23    chevrolet  c1500 suburban 2wd    6.0  2008    8   
23           24    chevrolet            corvette    5.7  1999    8   
24           25    chevrolet            corvette    5.7  1999    8   
25           26    chevrolet            corvette    6.2  2008    8   
26           27    chevrolet            corvette    6.2  2008    8   
27           28    chevrolet            corvette    7.0  2008    8   
28           29    chevrolet     k1500 tahoe 4wd    5.3  2008    8   
29           30    chevrolet     k1500 tahoe 4wd    5.3  2008    8   
..          ...          ...                 ...    ...   ...  ...   
204         205       toyota   toyota tacoma 4wd    3.4  1999    6   
205         206       toyota   toyota tacoma 4wd    4.0  2008    6   
206         207       toyota   toyota tacoma 4wd    4.0  2008    6   
207         208   volkswagen                 gti    2.0  1999    4   
208         209   volkswagen                 gti    2.0  1999    4   
209         210   volkswagen                 gti    2.0  2008    4   
210         211   volkswagen                 gti    2.0  2008    4   
211         212   volkswagen                 gti    2.8  1999    6   
212         213   volkswagen               jetta    1.9  1999    4   
213         214   volkswagen               jetta    2.0  1999    4   
214         215   volkswagen               jetta    2.0  1999    4   
215         216   volkswagen               jetta    2.0  2008    4   
216         217   volkswagen               jetta    2.0  2008    4   
217         218   volkswagen               jetta    2.5  2008    5   
218         219   volkswagen               jetta    2.5  2008    5   
219         220   volkswagen               jetta    2.8  1999    6   
220         221   volkswagen               jetta    2.8  1999    6   
221         222   volkswagen          new beetle    1.9  1999    4   
222         223   volkswagen          new beetle    1.9  1999    4   
223         224   volkswagen          new beetle    2.0  1999    4   
224         225   volkswagen          new beetle    2.0  1999    4   
225         226   volkswagen          new beetle    2.5  2008    5   
226         227   volkswagen          new beetle    2.5  2008    5   
227         228   volkswagen              passat    1.8  1999    4   
228         229   volkswagen              passat    1.8  1999    4   
229         230

In [359]:
pd.read_csv('k.csv')

'name'  'vale1' 'value2' 'value3'
0       1  kishore     ravi    name1
1       2    name2    name3    name4

In [363]:
print(dir(pd.pandas),end="")

['Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NaT', 'Panel', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseArray', 'SparseDataFrame', 'SparseDtype', 'SparseSeries', 'TimeGrouper', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_hashtable', '_lib', '_libs', '_np_version_under1p13', '_np_version_under1p14', '_np_version_under1p15', '_np_version_under1p16', '_np_version_under1p17', '_tslib', '_version', 'api', 'array', 'arrays', 'bdate_rang